### ISSUE TITLE
Save button does not work 

### ISSUE THREAD

**Issue by monitorjbl** [monitorjbl/pr-harmony#15]
Linked from review by Kedar Sarmalkar

**Comment by ksarmalkar** [comment]
Great .. i was about to email, this is much better. We are using Stash v3.8.0, Stash is in english. When I enter reviewer LDAP name or even full name, and hit save nothing happens, and when I visit the addon configuration page again, its not saved.

path of repo is in this format

https://stash.dev.company.com/projects/FLT/repos/library-project-name/

**Comment by monitorjbl** [comment]
Hm, I wonder if the Javascript for that page doesn't like that your path begins at `/`. Let me give that a shot locally and see if I can replicate this.

**Comment by monitorjbl** [comment]
Oh! Are you entering the user id or the like the full user name? The config only accepts the id, if you're looking at the Create User screen in stash, it's the contents of `Username` field: 

![image](https://cloud.githubusercontent.com/assets/1149136/9343517/81829514-45d0-11e5-8afd-4d131103a6dc.png)

This is made a lot simpler in the current development version, thanks to issue #9 's autocomplete feature.

**Comment by monitorjbl** [comment]
Also, and this is specific to external users, Stash is only aware of users that have logged in or have been created manually. If you are hooked up to LDAP and you try to add a user that has not logged in before, Stash won't have a record of him and the autovalidation the plugin does will simply remove that user from the config.

If you could, try adding your current user and see if that works.

**Comment by ksarmalkar** [comment]
We have LDAP configured .. and I'm just trying to add the LDAP user name and hit save, but nothing happens.

**Comment by monitorjbl** [comment]
So the problem is that I can't tell from your responses if that user actually exists in Stash, which is a requirement. The plugin will automatically filter out invalid usernames (i.e., users that do not exist in Stash). LDAP users only exist in Stash _after_ they log in.

If you try adding an LDAP user that you know for certain has logged in before (I was hoping your user would fit that description), it should verify if the plugin is doing something erroneously. Again, I think the fix for #9 will make this a lot clearer for users as it will only let you choose valid usernames in the UI.

**Comment by ksarmalkar** [comment]
Yes the users does actually exist in stash as as stash users, concluding from the number of licenses that went down after we enabled certain users (using LDAP). Another thing is the group name or username autocomplete does not work either.

**Comment by monitorjbl** [comment]
Do the other fields save properly?

**Comment by monitorjbl** [comment]
Forgot to mention, the autocomplete feature is not available in 1.6. It's going to be part of 1.7, which is not released yet. The beta version is available here to try if you'd like to: https://github.com/monitorjbl/pr-harmony/releases/tag/v1.7-RC1.

**Comment by ksarmalkar** [comment]
Hmm, no nothing saves. I will wait for 1.7 release

**Comment by monitorjbl** [comment]
@ksarmalkar that sounds good, you'll at least be able to verify that the users are going to pass validation in the backend. A thought just occurred to me, what browser are you using? The settings update action is asynchronous, and older browsers might have an issue with it.

**Comment by monitorjbl** [comment]
@ksarmalkar The latest release is now available. If you're still using Stash 3.x, can you give it a shot and see if that fixes the issue for you?

**Comment by ksarmalkar** [comment]
great will try it out. Thanks for all your effort.

**Comment by monitorjbl** [comment]
@ksarmalkar Did that work for you?

**Comment by ksarmalkar** [comment]
Hey I have asked my devops team to update the plugin. Will update you shortly.

**Comment by monitorjbl** [comment]
@ksarmalkar A similar problem was reported by a user using LDAP with uppercase usernames. If you're using Bitbucket Server 4.0+, can you give the latest version of this plugin a shot?

**Comment by monitorjbl** [comment]
@ksarmalkar Any update? If not, I'm going to close out this issue.

**Comment by ksarmalkar** [comment]
We have latest update, tried adding user at repository level, no luck saving it. on hitting save it just clears the last thing I added.

**Comment by ksarmalkar** [comment]
Nm, I was wrong, seems like this is working now. Thanks for the updates.

**Comment by monitorjbl** [comment]
Glad to hear it! Don't suppose you'd be willing to update your review on the marketplace now, would you? :)

**Comment by ksarmalkar** [comment]
Oops I totally forgot I had rated it, updated to 4 now .. but unfortunately cannot update my review text.

**Comment by monitorjbl** [comment]
Thanks! I'm gonna close this issue out now, appreciate you revisiting this!
