### ISSUE TITLE
Required users should still have to have approvers

### ISSUE THREAD

**Issue by monitorjbl** [monitorjbl/pr-harmony#16]
The required users are treated as trusted and their submissions count as already having one approval. This works if there is only one required approver, as there would be no one else to approve the PR. However, in the case where there are multiple approvers, this pattern essentially puts reviewers above each other.

If the number of required reviewers is greater than the number of required reviews, PR submissions made by the required reviewers should still require reviews (think I can squeeze another 'review' in there?).

**Comment by mnhorak** [comment]
+1 Sounds great. Did take me a few times reading through it to understand it, but you got it right. This feature would be really useful for my team.

**Comment by monitorjbl** [comment]
Haha, yeah I couldn't get around the awkward wording of that :(

**Comment by rogerbramon** [comment]
+1 

If the one who open the PR is the only one who can approve it, it seems to me a configuration problem than a requirement that the plugin should treat.

**Comment by monitorjbl** [comment]
Sorry for the lack of updates, I've been pretty busy the last few weeks and haven't had a ton of time to work on this particular issue. I'm going to push this out to the next release, as I really want to get the current one out the door. It's starting to get pretty big and I want to make sure it's finished before I start monkeying around with core stuff.

**Comment by ghost** [comment]
I found the required users section to be confusing.  It might make sense to change the wording to something like "trusted users for required reviews", similar to the wording you are using above.

**Comment by monitorjbl** [comment]
@majgis I tried making it a little clearer in this commit: e0cfd3f
