### ISSUE TITLE
Does not work when target repo is a fork

### ISSUE THREAD

**Issue by ghost** [monitorjbl/pr-harmony#17]
Default reviewers are not populating

Error in browser log when creating a PR: 
GET http://<server>/rest/pr-harmony/1.0/users// 404 (Not Found)

Any suggestions on what to look for?

Atlassian Stash v3.10.4

**Comment by monitorjbl** [comment]
Well, that's interesting...what is the full path to your Stash instance?

**Comment by ghost** [comment]
http://build01.test.something.com:7990/rest/pr-harmony/1.0/users//
http://build01.test.something.com:7990/projects

**Comment by monitorjbl** [comment]
Sorry, I meant like to something in the UI. Like the path to your repo.

**Comment by ghost** [comment]
http://build01.test.something.com/users/majgis/repos/test/browse

It is a repository under my profile (not a project).

**Comment by ghost** [comment]
I confirmed that this issue only occurs for repositories under a user profile.  I created a project and did a PR and everything worked fine.

**Comment by monitorjbl** [comment]
Hm, that's interesting. I never tested for that explicitly but I'm kind of surprised it doesn't work. I'll have to take a look this weekend.

**Comment by ghost** [comment]
It isn't a deal breaker for our team, but it would be great to have a fix
before we deploy it.

I appreciate that you continue to maintain this project.  Thanks you for
looking into it!

**Comment by monitorjbl** [comment]
@majgis I published an [RC version](https://github.com/monitorjbl/pr-harmony/releases/tag/v1.7-RC3), would you be able to install it and see if it addresses your issue?

**Comment by ghost** [comment]
Thank you.  I will look into testing the RC version.

**Comment by ghost** [comment]
I was able to test v1.7-RC3 and I no longer see the issue.  Thank you!
