### ISSUE TITLE
Excluded Groups in Branch Protection Options does not work

### ISSUE THREAD

**Issue by indrgun** [monitorjbl/pr-harmony#18]
We have a use case where the "mainline" branch should be restricted to all users except CI builder user and set of users act as repository admins.

The CI builder user and set of users all are included in a Stash group mapped to AD group.

I am already a member of this admin group.  

If in a repository PR Harmony setting I specify:
1.  mainline branch in "Block Direct Commits" and 
2. the "repo-admin" group in Excluded Groups.  
I am still unable to push directly to the mainline.

remote:
remote: ******************************
remote: \*    !! Commit Rejected !!   *
remote: ******************************
remote:
remote: Direct commits are not allowed
remote: to branch [<branch-name>].
remote: 

If instead:
a repository PR Harmony setting I specify:
1.  mainline branch in "Block Direct Commits" and 
2. my stash user-id in "Excluded Users" 
Then, I am able to push directly to the mainline.

Our Stash runs version 3.6.1

Thank you
-Indra

**Comment by monitorjbl** [comment]
Yep, can confirm. Looks like a pretty simple omission, I'll get it included in release 1.7.
