### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by monitorjbl** [monitorjbl/pr-harmony#19]
The plugin should support the latest version of Stash, which has been renamed Bitbucket.

**Comment by mnhorak** [comment]
We're going to hold off upgrading to 4.0 (Bitbucket Server, thanks branding dept) until more add-ons are supported. Glad you're looking into it!

**Comment by ghost** [comment]
Thank you for planning to support Bitbucket server.  We should get a test server up next week, so I hope to help you with testing.

**Comment by monitorjbl** [comment]
Just a quick update, I am working on this but documentation on the new Bitbucket APIs is still a bit muddied with the old Stash ones so it's been kind of slow going to find the replacements. It's currently working except for the Javascript hooks I added in version 1.7. 

When I get that working and reasonably tested locally, I'd really like to get some confirmation that everything is working for at least one or two other people before I release it to the Marketplace. It sounds like @majgis is willing, would anyone else like to?

**Comment by ghost** [comment]
Yes, I'm in, our test server is ready and waiting.

**Comment by monitorjbl** [comment]
@majgis I put up a release candidate here: https://github.com/monitorjbl/pr-harmony/releases/tag/v2.0-RC1. Let me know if you run into any issues!

**Comment by ghost** [comment]
I'm working on getting it installed on our test server now.  I'll let you know if I find anything.

**Comment by ghost** [comment]
I was able to test everything except features around groups, due to limitations on our test server.  Otherwise, I tested against both projects and user profile repos, and I found no issues.  Thank you!

**Comment by monitorjbl** [comment]
Version 2.0 is now available in the Marketplace. Thanks for helping test @majgis !
