### ISSUE TITLE
Automerged branches are not automerged when a build completes

### ISSUE THREAD

**Issue by monitorjbl** [monitorjbl/pr-harmony#2]
If a PR is approved and waiting on a build to complete before merging, the automerge functionality does not detect when the build completes successfully.

**Comment by monitorjbl** [comment]
For reference, as of Stash 3.6.1 there is no event to listen to for builds.

**Comment by monitorjbl** [comment]
It looks like it's possible to have an event listener for all build events: https://developer.atlassian.com/static/javadoc/stash/3.10.0/build-integration/reference/com/atlassian/stash/build/BuildStatusSetEvent.html

**Comment by davfifa** [comment]
Just wonder if there is no build associated with the repo, will a PR get auto-merged? Seems not working here.

**Comment by monitorjbl** [comment]
The plugin listens only to approval events in the latest release. This is fine for simple cases, but if you've configured your repo to block PRs until there's a successful build then the PR won't automerge. It's kind of a pain if you've got a full CI workflow. 

There is a build complete event hook as of Stash 3.9.1. With that, the plugin can trigger an automerge if the PR is approved.

**Comment by monitorjbl** [comment]
I'm going to wait to fix this until version 1.5. It will break compatibility with Stash 3.6 and I want to get the other issues for 1.4 resolved without requiring a version upgrade of Stash.
