### ISSUE TITLE
Merge button is not automatically enabled when approve criteria are met

### ISSUE THREAD

**Issue by j-vizcaino** [monitorjbl/pr-harmony#21]
How to reproduce:
- configure PR-Harmony to allow PR to be merge when at least 1 dev has approved
- go to PR, merge button is disabled (because it needs approval from 1 person in the list)
- click approve (you are one of the mandatory reviewers)
- merge button is still disabled.
- refresh the page, the merge button is now enabled

**Comment by monitorjbl** [comment]
@j-vizcaino yeah, this is definitely a known issue with Stash. Basically, clicking Approve doesn't force the UI to recheck if the PR is mergable. PR Harmony could have a Javascript hook to force a page reload on approval events though.
