### ISSUE TITLE
Settings screen doesn't show text fields

### ISSUE THREAD

**Issue by cooksimo** [monitorjbl/pr-harmony#25]
<img width="845" alt="screen shot 2015-11-13 at 5 12 23 pm" src="https://cloud.githubusercontent.com/assets/1697654/11138656/f928a106-8a29-11e5-8c72-a8052289403b.png">

As seen in the attached screenshot, half the text fields are missing from the configuration screen.

**Comment by monitorjbl** [comment]
What browser are you using?

**Comment by monitorjbl** [comment]
Also, what Stash/Bitbucket version?

**Comment by cooksimo** [comment]
This was using Safari and Stash version 3.8.1

**Comment by cooksimo** [comment]
Any ideas on this?

Our setup has all users coming from an LDAP directory, could that be the issue?

**Comment by monitorjbl** [comment]
No, I don't think so. We use that as well with no issue. It looks like the Select2 fields are the missing ones, but I couldn't tell you why that is. I can't reproduce this on version 1.8 of the plugin. Have you done any special customization to your Stash installation?

**Comment by cooksimo** [comment]
Not that I can recall - can you suggest any settings I could check to see if they are causing this?

**Comment by monitorjbl** [comment]
Hmm... Not really :( The only other thing I'd suggest is looking at your browsers Javascript console when you load this page. 

The JS hook is loading the Select2 plugin through the Atlassian UI framework. The only reason it would render like this is if something went wrong in loading that plugin.

**Comment by cooksimo** [comment]
Had a look in the log, here is what I see:

`Mixed Content: The page at 'https://stash/plugins/servlet/pr-harmony/RE/repo' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://stash/rest/pr-harmony/1.0/config/RE/repo'. This request has been blocked; the content must be served over HTTPS.`

**Comment by monitorjbl** [comment]
Ah, that would explain it. Something in your environment is not configured properly for HTTPS, so the plugin endpoint is being requested over HTTP. We use HTTPS where I work, so I'm fairly sure the plugin isn't the culprit. Let me see if I can give you a pointer to the config it's referring to.

**Comment by monitorjbl** [comment]
It's referring to `$applicationProperties.getBaseUrl()` here: https://github.com/monitorjbl/pr-harmony/blob/master/src/main/resources/repo-config.html#11. I'm not sure what specific Stash/Bitbucket config item that refers to, is there anything on your servers Co fig that specifies the base URL?

**Comment by cooksimo** [comment]
Fixed this, it was a config error trying to proxy https
