### ISSUE TITLE
Is support for Data Center on the roadmap?

### ISSUE THREAD

**Issue by gawlik** [monitorjbl/pr-harmony#28]

**Comment by monitorjbl** [comment]
I don't currently have a very good way to develop or test for Stash Datacenter, so as far as official support goes it likely won't be anytime soon. But the plugin may work there, have you tried it?

**Comment by gawlik** [comment]
Thanks for the quick response. 
![image](https://cloud.githubusercontent.com/assets/366859/11460592/551d9e72-96ef-11e5-8e26-e7c6d0ca8f67.png).

Probably the issue below is related with missing compatibility with DataCenter:
https://github.com/monitorjbl/pr-harmony/issues/20

**Comment by carlmot** [comment]
Another request for Data Center compatibility. Cannot use it without that.
