### ISSUE TITLE
Reviewers should appear immediately on opened PRs

### ISSUE THREAD

**Issue by josephearl** [monitorjbl/pr-harmony#3]
Stash version: 3.3.1
PR Harmony version: 1.2

Expected:
1. Enter comma separated list of usernames in default reviewers configuration
2. Save configuration
3. Open new pull request
4. Users entered in the first step appear in the Reviewers entry field

Actual:
Reviewers entry field is empty

Have tried with just a single username.

**Comment by monitorjbl** [comment]
Is the Default Reviewers field empty after you click save? The users you submit are validated in the system, and any that don't exist are removed.

**Comment by monitorjbl** [comment]
Also, the reviewers on the pull request may not show up immediately. They're added asynchronously, so you may have to refresh the page after you open the PR to see them.

**Comment by josephearl** [comment]
> Is the Default Reviewers field empty after you click save? The users you submit are validated in the system, and any that don't exist are removed.

Ah, they do appear on the created PR! Thank you.

Howevever, I have one user with a name with capitals, MPerzak. If I enter it like that into the PR Harmony configuration field, it removes it once I click save. If I enter it as mperzak, it is saved, but when I create a PR that user does not appear.

**Comment by josephearl** [comment]
On the create screen - I've tried waiting a while and also refreshing, but the Reviewers form field is never filled.

![screen shot 2015-06-03 at 12 40 37](https://cloud.githubusercontent.com/assets/2513147/7959097/e1a31a1e-09ed-11e5-8df1-eac6913ee8cd.png)

**Comment by josephearl** [comment]
What I expected was:
- On the create PR page the Reviewers field is filled (perhaps asynchronously, but I'd expect with a few second of loading the page)
- On the PR page the Reviewers are immediately visible

Happy to look into submitting a PR if you think it would be possible to make improvement.

**Comment by monitorjbl** [comment]
I don't think there's a way to populate the reviewers field on the create window. The event system that the plugin uses only issues an event on PR creation, and I've never seen a UI hook for that modal window. I'd love to be proved wrong on that, but I'm not terribly optimistic about it. 

The asynchronous loading is also one of those things that I don't think you can get around directly. It's just the way the Java API works; Atlassian doesn't want you to things synchronously unless absolutely necessary. However, it may be possible to inject some Javascript onto the PR page that does an automatic refresh on create. I've seen plugins that add buttons and other UI elements to that page.

**Comment by josephearl** [comment]
If you see my image above, I have a plugin, Stash Reviewer Suggester, that added the suggested name below the Reviewers field on the create PR screen. Source is here https://bitbucket.org/atlassian/stash-suggest-reviewers/ in case it is useful.

**Comment by monitorjbl** [comment]
I opened #4 for lowercasing usernames, is it alright if I rename this issue to "Reviewers should appear immediately on opened PRs"?

**Comment by josephearl** [comment]
Yes that sounds like a better title

**Comment by monitorjbl** [comment]
Oh, awesome! I'll take a look after work and see what I can do with that, thanks for sharing!

**Comment by monitorjbl** [comment]
Forgot to mention, if you'd like to submit your own PR you're definitely welcome to do so. It sounds like you're more familiar with the part of the API that allows this than I am. I was thinking it would make sense to just add a feature to populate the Reviewers field in the UI. The async stuff could stay in place to make sure that the required reviewers are always present.

**Comment by josephearl** [comment]
If I get some time I'll have a go, might not be until the weekend -- what I was hoping is that it would be possible to fill the box on the Create PR screen, so that the logic for the PR screen itself wasn't needed

**Comment by monitorjbl** [comment]
It'd be a validation kind of thing. The required reviewers should always be present, even if the user doesn't select them.

**Comment by josephearl** [comment]
Ah yes, if the user removed them from the input field. Alternatively it might be possible to prevent a user creating a PR that didn't have the required reviewers.

**Comment by monitorjbl** [comment]
Took a shot at implementing this tonight, I had no idea you could hook into so many different pages with the Stash API! It's working for me locally @JosephEarl if you want to take a look on your version of Stash. I'm going to aim to get #1 and #4  done before I release this out to the marketplace anyway.

**Comment by josephearl** [comment]
Great! Took you no time at all.
I'll see if I can get it installed on our Stash instance today and give it a run.

**Comment by monitorjbl** [comment]
I released 1.3 out to the marketplace today, which includes this feature. If you have feedback about it, just open a new issue.

**Comment by josephearl** [comment]
Checked it out - works great

**Comment by josephearl** [comment]
Has there been a regression in 1.4? I'm no longer seeing this behaviour but the old pre 1.3 behaviour (added asynchronously after PR has been created)

**Comment by monitorjbl** [comment]
No,  there shouldn't have been. What version of stash are you using?

**Comment by josephearl** [comment]
3.3.1

**Comment by monitorjbl** [comment]
That technically isn't supported by the plugin. The compatibility range is 3.6.1-3.9.1. I'll take a look at this when I get home, but as far as I'm aware nothing changed here.

**Comment by josephearl** [comment]
That gives me more of a reason to push DevOps to upgrade :)
On 30 Jun 2015 18:42, Taylor Jones notifications@github.com wrote:That technically isn't supported by the plugin. The compatibility range is 3.6.1-3.9.1. I'll take a look at this when I get home, but as far as I'm aware nothing changed here.

**Comment by monitorjbl** [comment]
Just a quick update, I noticed today that the marketplace has started listing compatibility ranges for the plugin that I [definitely did not set](https://marketplace.atlassian.com/plugins/com.monitorjbl.plugins.pr-harmony/versions) and certainly have not tested with. Months-old versions are showing compatibility with the latest Stash release (3.11.1) which came out two weeks ago. The setting range I always give is 3.6.1-3.9.1 because that's what I test with.

I'll be reaching out to Atlassian to figure out what's going on there and make sure it doesn't happen again. Hopefully you've updated anyway, but if you saw these erroneous values I hope it didn't cause any confusion.
