### ISSUE TITLE
Empty user list on creating PR

### ISSUE THREAD

**Issue by bjmillar** [monitorjbl/pr-harmony#31]
We would really like to use this plugin but we are having some issues. Our setup:
- Bitbucket Server v4.2.0
- PR Harmony v2.1

I have tried all combinations of project and repository settings for PR Harmony but no matter what, the reviewer list is empty when creating a PR. I have noted other similar issues (now fixed) as we have non-lowercase repositories and users in Bitbucket. Everything else works correctly, including the merge check for the required reviewers!

Some things to note:
- http://192.168.161.57:7990/rest/pr-harmony/1.0/users/aoc/aocom responds but with no users listed
- http://192.168.161.57:7990/rest/pr-harmony/1.0/config/AOC/AOCOM repsonds with the correct configuration (the repository and project are all uppercase)
- http://192.168.161.57:7990/rest/pr-harmony/1.0/config/AOC/aocom repsonds with the correct configuration
- but http://192.168.161.57:7990/rest/pr-harmony/1.0/users/AOC/aocom responds with error 500 and a NPE.

On the PR create screen the browser log reports "Fetching required users" but not "Loaded required users".

I tried with all sorts of combination of lowercase projects, repositories and users but to no avail.

Regards,
Barry.

**Comment by monitorjbl** [comment]
Interesting, I haven't seen this before. Let me take a look at your examples and see if I can replicate them.

**Comment by bjmillar** [comment]
I am in the middle of trying to migrate our projects/engineers to Bitbucket/Git so I am happy to help if you have any debug or RCs you want to try out.

**Comment by bjmillar** [comment]
I blanked all the settings in the PR Harmony config pages for my repository and for the project so that it was effectively unused and now I get blank pages when attempting to open the PR Harmony config pages of the project and the repository.

**Comment by intiocean** [comment]
I'm seeing a similar issue where no reviewers are filled in.

Same versions as above but I don't see anything logged to the browser console.

![image](https://cloud.githubusercontent.com/assets/725843/12331891/82c60cf2-bae3-11e5-81b9-04eabfe5b1a0.png)

**Comment by monitorjbl** [comment]
@intiocean Are you setting the Default Reviewers field in the configuration? Required reviewers are not automatically added to all PRs.

**Comment by monitorjbl** [comment]
@bjmillar I'm not able to replicate this locally. I am able to confirm case-sensitivity matters, but the plugin ought to use the case that your repos have. What is the actual value for your project key and your repo slug?

For reference, this is what I see with those repo names:

![image](https://cloud.githubusercontent.com/assets/1149136/12369853/2e94c228-bbcd-11e5-8f37-10adb679c0f4.png)

And here's my config:

![image](https://cloud.githubusercontent.com/assets/1149136/12369856/41662914-bbcd-11e5-908d-bd47b7ccc462.png)

Note that the "Default users" is set. This is what populates the PR on creation. You mentioned that you're not seeing the "Loaded required users", which is kinda odd. If you're not seeing any errors in your console, it _could_ be a result of a misconfiguration on the server. A user did see issues when using HTTPS, he didn't have the server name value set properly on the Stash side so the plugin tried to communicate over HTTP and the browser blocked it with a warning.

Based on the URLs you posted, I don't think that's the case. If you're not seeing anything obviously odd, would you mind pasting a screenshot of your browser's network and Javascript console?

**Comment by Wilfred** [comment]
I'm consistently encountering this bug.

I set the default reviewers:

![pr_harmony_settings](https://cloud.githubusercontent.com/assets/70800/12389892/c250e32c-bdd3-11e5-9fd6-593a7ce72b3b.png)

However, when I create a pull request, no reviewers are added:

![pr_harmony_reviewers](https://cloud.githubusercontent.com/assets/70800/12389903/d17bdd70-bdd3-11e5-9a1f-5cdd9806b143.png)

There are no HTTP error codes in the network logs:

![pr_harmony_network](https://cloud.githubusercontent.com/assets/70800/12389910/dece9ff8-bdd3-11e5-94d1-02ea45f382e8.png)

and there are no errors in the browser console either:

![pr_harmony_console](https://cloud.githubusercontent.com/assets/70800/12389916/eaa3cfba-bdd3-11e5-98d5-0d1e1b6c435e.png)

**Comment by monitorjbl** [comment]
Thanks for documenting this so clearly. I do see one odd thing in the console log. The "HERE I AM" line is a debug line I accidentally left in on the last release. It shows up in its own Javascript file on my environment but it's showing up in a batch.js file in yours. I wonder if whatever setting causes that to happen is interfering with the Javascript hook.

**Comment by monitorjbl** [comment]
I added a lot of extra debug output in the latest code which should hopefully help pinpoint what's going on in your environments that's causing this problem. If you have a few minutes, I've posted a build that you can download and install manually [here](https://github.com/monitorjbl/pr-harmony/releases/tag/v1.8.2-debug). Once you've got it installed, you should be able to open up your browser's dev console and see a bunch of lines that look like this: 

![image](https://cloud.githubusercontent.com/assets/1149136/12404251/ca05119a-be07-11e5-9fa3-e122e6be7137.png)

If you could post the entire output into this issue, it would be a huge help to figuring out what's causing this bug for some users.

**Comment by bjmillar** [comment]
Thanks for the debug version. Sorry I didn't get back to you yesterday. I have attached the results of some of my tests. It looks like it is a user "type" issue. We have some local users for admin/CI purposes. However the majority of our actual users login using "JIRA Server". From the various tests attached you can see that a "JIRA Server" user cannot amend the PR Harmony config - nothing is rendered. Also when at least one "JIRA Server" user is added to the list of reviewers, the reviewer list is empty when creating a PR. When I use entirely local users it all works fine.

Let me know if you need me to throw in some more debug or try anything different.

[prh-debug.txt](https://github.com/monitorjbl/pr-harmony/files/95669/prh-debug.txt)

**Comment by bjmillar** [comment]
Oops. Just noted that the "Result" of "TEST 5" in my attachment above states "Nothing is rendered". This is incorrect as the configuration was correctly rendered and populated.

**Comment by monitorjbl** [comment]
Ah, we don't use Jira as a user repository, so I guess that's the difference. I'll see if I can reproduce this with the SDK

**Comment by Wilfred** [comment]
Interesting that it might be related to the user type. On our test system, users log in with LDAP accounts.

**Comment by bjmillar** [comment]
Ours do too, but via JIRA as Bitbucket uses it as a user directory.

**Comment by monitorjbl** [comment]
@Wilfred Would you be able to try out the version with debug logging?

**Comment by bjmillar** [comment]
Yes I can.

**Comment by bjmillar** [comment]
Might have misunderstood. Would you like me to run Bitbucket with debug or is there a setting to enable debug for the plugin?

**Comment by monitorjbl** [comment]
@bjmillar Thanks but you've already given me your debug output. I was asking @Wilfred if he could send me his as well. We use LDAP but not the latest version of Bitbucket where I work, and I haven't been able to replicate this issue using the SDK yet.

**Comment by monitorjbl** [comment]
Atlassian accidentally broke the plugin persistence storage API from 4.0 to 4.1 so it's possible they've broken something with security in 4.1 to 4.2.

**Comment by Wilfred** [comment]
OK, I've installed the 2.2 snapshot and it seems to be working! Bizarre. Downgrading to 2.1 makes the issue reappear.

@monitorjbl would you still like the debug logging?

**Comment by Wilfred** [comment]
OK, I suspect I can see the issue.

c6160b4f5cd64d1c1ab60ac992102a760b7eabde made the following change:

``` diff
-define('suggested-reviewers', [
+define('pr-harmony-create', [
```

However, Atlassian's [suggest reviewers plugin defines a module of the same name](https://bitbucket.org/atlassian/stash-suggest-reviewers/src/55fe64031dac34aa6fb1e5a8a07f46c57db6730d/src/main/resources/js/suggest-reviewers.js?at=master&fileviewer=file-view-default). We have this plugin installed, so I think its JS is overriding pr-harmony's JS.

**Comment by monitorjbl** [comment]
Ah, interesting! I wonder why @bjmillar still has trouble though...

**Comment by bjmillar** [comment]
@monitorjbl I have had another play with this to see why I am having issues. The 2 issues I suffer are:
1. I get a blank config page for LDAP (via JIRA) users and it works for my local users.
2. If I add any LDAP users to any of the reviewer lists in the config, they do not appear in the PR create.

I just noticed that _all_ my LDAP users are capitalised (of the form T0123456) and all my local Bitbucket users are entirely lowercase.

Luckily, I have access to one other LDAP account. I added that LDAP user to JIRA as e.g. "Server_user". When I logged into Bitbucket using this account I got the issues above. I deleted this user from JIRA and added the LDAP user into JIRA again, this time as "server_user" (all lower case!). When I logged into Bitbucket the config page was again available to me.

I added the "server_user" to the list of required users on my test project. I then logged on as one of local users to create a PR on a branch in this project. The PR create button was disabled and a correct warning was displayed about missing required users. I added the required user and the warning was removed. The required user was not automatically added to the list of reviewers. Should it be? I repeated the test using the "server_user" as a default user. In the PR Create this user was correctly prepended to the list of reviewers.

Am I suffering because of the case of the LDAP users? I know there were changes made previously as a result of the case of users. I noticed from the code that ConfigDao still "lowercases" users in method FilterInvalidUsers.apply(). As I am getting a 403 error from the config page when using LDAP users with uppercase, is this the problem?

**Comment by monitorjbl** [comment]
That's certainly something I can try to reproduce. I'll give it a shot, hopefully that's the culprit. I haven't seen any evidence that the origin of the user would make any difference.

**Comment by monitorjbl** [comment]
Awesome, it looks like I can reproduce this now! This is my configuration:

![image](https://cloud.githubusercontent.com/assets/1149136/12697170/75c4a3c4-c74a-11e5-8a2d-98ce52444813.png)

And this is what I see when I try to create a PR:

![image](https://cloud.githubusercontent.com/assets/1149136/12697173/8738a650-c74a-11e5-98ef-0d4c3ac2660d.png)

It looks like there's an NPE being thrown. You can see this in the browser logs 

![image](https://cloud.githubusercontent.com/assets/1149136/12697191/eb9cad44-c74a-11e5-8551-54ef514c761e.png)

or the server logs

![image](https://cloud.githubusercontent.com/assets/1149136/12697174/a03783ba-c74a-11e5-91c7-f4af2802a3f3.png)

It would appear that the [user lookup service](https://github.com/monitorjbl/pr-harmony/blob/master/src/main/java/com/monitorjbl/plugins/UserUtils.java#L29) from Atlassian doesn't handle uppercases anymore. This worked previously, in fact issue #5 involved uppercases and a user confirmed the fix to work. Switching to `userService.getUserByName(username)` seems to work for both cases. 

I published a [release candidate](https://github.com/monitorjbl/pr-harmony/releases/tag/v1.8.2-RC1) with this fix, would be able to give it a shot and see if it works for you?

**Comment by bjmillar** [comment]
@monitorjbl I have tried the RC. So the Create PR option now works as expected. The default users appear in the list of reviewers and a warning is displayed if the required users are not entered in the list of reviewers. However, I can only access the PR-Harmony configuration page if I log on as a "lower case" user. If I go to the configuration page as one of my uppercase users I see nothing.

**Comment by monitorjbl** [comment]
Shoot, must be a similar issue. Should be easy enough to replicate and fix.

**Comment by monitorjbl** [comment]
Yep, it turned out to be pretty easy to fix. I put a [new RC version](https://github.com/monitorjbl/pr-harmony/releases/tag/v2.2.0-RC2) up, if you can give that a quick try I'll go ahead and release this fix to the marketplace.

**Comment by bjmillar** [comment]
@monitorjbl  I have tested the latest RC and the config and PR Create now works for all users. Thank you very much for your support and persistence in getting this resolved.

**Comment by monitorjbl** [comment]
Version 2.2.0 is now live on the Atlassian Marketplace. Thanks to everyone that helped debug this issue!

**Comment by AkulBhatnagar** [comment]
I feel blessed that I found this page. But there is a bad news, I could see similar issue (LDAP user) in PR Harmony current release 2.3.1 which is available at Atlassian Market Place.

I even tried 2.2-RC jar. But it failed too.
https://github.com/monitorjbl/pr-harmony/releases/tag/v2.2.0-RC2

Please note, I use bitbucket 4.3.2

**Comment by andyliu38** [comment]
I think I'm experiencing the same thing, however, I'm using PR Harmony 2.3.1 with bitbucket server v4.10.1.

I notice in IE11, the default reviewer group are not added at p/r creation even though a default review group is set/saved. But this issue is fine in FireFox and Chrome. IE Compatibility setting seems like is not the culprit. My username is all capitalized.  And the default review group I have there is a mix of username in all upper and all lower cases.

Thought? Thanks.
