### ISSUE TITLE
Please release with fixed JS namespace

### ISSUE THREAD

**Issue by Wilfred** [monitorjbl/pr-harmony#32]
As discussed in [this comment on #31](https://github.com/monitorjbl/pr-harmony/issues/31#issuecomment-175755629), the changes in c6160b4f5cd64d1c1ab60ac992102a760b7eabde fixed pr-harmony on Bitbucket Server instances where the suggest reviewers plugin is also installed.

As a result, v2.2-SNAPSHOT works nicely on our setup. Could you do a release so we can roll it out to our production machines?

**Comment by monitorjbl** [comment]
I'm going to give #31 a few more days to see if we can resolve @bjmillar's issue. I'll plan on releasing either way by Monday.

**Comment by monitorjbl** [comment]
Version 2.2.0 is available for download with the fixed namespace!
