### ISSUE TITLE
403 When viewing plugins/servlet/pr-harmony/*

### ISSUE THREAD

**Issue by ghost** [monitorjbl/pr-harmony#33]
We're receiving a 403 in one of our environments with with PR-Harmony enabled.  This is occurring on an instance with a self signed SSL and on all directories.  It returns a 403 both behind and in front of SSL.  This is occurring on Stash version 3.11.1 and plugin version 1.8.2

Is there any way to enable debugging as there is nothing being pushed to the atlassian-stash.log or catalina.out.

**Comment by monitorjbl** [comment]
There wouldn't be any log events on the server for this kind of error. I would check the browser's dev console to see what errors are being thrown. 

I suspect that your Stash instance is misconfigured somewhere and thinks that its URL is HTTP instead of HTTPS. Your browser's dev console should report the URL that threw the 403, can you paste it in this issue?

**Comment by ghost** [comment]
The console shows a GET to https://stash.domain.com:8443/plugins/servlet/pr-harmony/AN
I've tested this in a couple of browsers, so far Chrome and Safari from my mac.  Safari is recognizing this as a document and downloading a blank file.  Internet Explorer in a windows browser says this page cannot be displayed, and the same with firefox.

Here's the full response with my SEN removed:
        "response": {
          "status": 403,
          "statusText": "Forbidden",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Wed, 17 Feb 2016 13:33:52 GMT"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff"
            },
            {
              "name": "Server",
              "value": "Apache-Coyote/1.1"
            },
            {
              "name": "X-AREQUESTID",
              "value": "@7FWUKAx393x1643574x2"
            },
            {
              "name": "X-ASEN",
              "value": "SEN-xxxxxxx"
            },
            {
              "name": "X-AUSERNAME",
              "value": "xxxxxxx"
            },
            {
              "name": "X-ASESSIONID",
              "value": "t243g8"
            },
            {
              "name": "Content-Length",
              "value": "0"
            },
            {
              "name": "X-XSS-Protection",
              "value": "1; mode=block"
            },
            {
              "name": "X-AUSERID",
              "value": "656"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/plain",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 294,
          "bodySize": 0,
          "_transferSize": 294
        }

Please let me know if there are any other things to check for.

**Comment by monitorjbl** [comment]
Does the rest of your server run from exactly https://stash.domain.com:8443? Stash does cookie-based Auth, so the protocol, hostname, and port must match exactly to those that users access from their browsers. If, for example, your users login on port 443, access to port 8443 will not be granted.

**Comment by ghost** [comment]
Our base URL is set to https://stash.domain.com:8443 and I log in on https://stash.domain.com:8443.  There is another listener on port 8080 that Atlassian asked us to setup during testing for some issues that we experienced in the past, but that is not generally used.  

If I log in on 8443, then go to 8080, I'm required to login again.

**Comment by ghost** [comment]
One more thing.  A colleague and I just did some testing.  It looks like if I login with an account that is all lowercase, then I can see this page; however, if the username has capital letters in it, I'm shown a 403 error.

**Comment by monitorjbl** [comment]
Ah, that's actually fixed in the latest version for Bitbucket (#31).  I didn't backport that fix to Stash. Do you have plans to upgrade soon?

**Comment by eabehrens** [comment]
I've put in a PR that backports (#31).  We do not have plans to upgrade soon enough unfortunately.  I wasnt sure of your branch management so if you need me to change something about the branch or PR let me know.

**Comment by monitorjbl** [comment]
Looks like someone just opened a PR to backport the change (#34) . I assume it's one of your colleagues. I'll test it out locally and try and get a release out by the end of the week.

**Comment by monitorjbl** [comment]
So, just a quick update: I can't release this to the marketplace yet, I accidentally made a typo in the version create screen and there isn't an option to undo it or to make a duplicate version with the same version number. I have to open a support case to have them take care of it. There is a released JAR file here that you can download in the meantime if you would like to get the officially released plugin: https://github.com/monitorjbl/pr-harmony/releases/download/v1.8.3/pr-harmony-1.8.3.jar.

**Comment by monitorjbl** [comment]
Version 1.8.3 is now available on the marketplace. Thanks for the PR!
