### ISSUE TITLE
Is not a User Error

### ISSUE THREAD

**Issue by frovirat** [monitorjbl/pr-harmony#36]
Hi,

I've installed Bitbucket server 4.4.1 and PR Harmony 2.3.0. over Windows 7 64-bits.

The issue is that when I've the reviewers users fulfilled automatically by PR Harmony in a Pull Request, once I click on Create button, the user Name "is not a user" error appears....but If I remove the users, and type it manually and getting the suggestions of the Bitbucket Server, works perfectly.

When the error appears I see that the name of the user in in lower case and the real name have an upper case letter....I don't know if it could be the problem....but if I log in to the server, using all lower case user name enters perfectly....

If it is need some more information, please ask me.

Thnks a lot!
    Ferran.

**Comment by frovirat** [comment]
Hi,

I've done this workaround...if I type the user name in lower case one of the reviewers, then the create Pull Request catch perfectly the user, and the one that is not renamed, the error  "is not a user" persist.

**Comment by monitorjbl** [comment]
I've had several defects pertaining to uppercase user names not working for various reasons. It sounds like a simple thing, but the backend API that is used to check for user existence seems to work one way in some versions and a different way in another. Can you paste in the usernames you're trying with? I'll see if I can replicate and fix this.

**Comment by gawlik** [comment]
We faced exactly the same issue while testing it. For the following username format the problem exists:
ABC123

**Comment by monitorjbl** [comment]
@gawlik @frovirat I pushed a fix that appears to work for the 'ABC123' example. Can you try a build of the latest code and see if it works for you now?

**Comment by gawlik** [comment]
Thank you, looks good and will continue testing. Thank you also for adding:
`<param name="atlassian-data-center-compatible">true</param>`
Can we expect the official release with these two changes soon? :)

**Comment by monitorjbl** [comment]
Yeah, if there's no reports of issues this week, I'll release the current code to the marketplace.
