### ISSUE TITLE
Default Groups/Required groups not working

### ISSUE THREAD

**Issue by floryut** [monitorjbl/pr-harmony#37]
I'm trying to add groups as default and required reviewers (like a tech team and a functionnal team) but I can't manage to do it using PR :( users works fine (the autocomplete find everybody) but group doesn't seems to work at all.

Am I missing something ? My groups are manage via JIRA but even local groups (stash internal) doesn't seems to get returned by the autocomplete.

BitBucket Server version 4.2.0
PR Harmony version 2.3.0

![stashpr](https://cloud.githubusercontent.com/assets/16313165/13643034/392b22a0-e61f-11e5-9c68-bdab7bdf4622.png)
![stashgroups](https://cloud.githubusercontent.com/assets/16313165/13643033/3921d2c2-e61f-11e5-9b0a-58b89108df60.png)

**Comment by ghost** [comment]
Experiencing the same.

**Comment by eabehrens** [comment]
Only if you didn’t add them to the project or repo though correct?

**Comment by monitorjbl** [comment]
Groups must be granted permission on the repo to show up in this dropdown. It's possible that some or all of the users in the group have access, but the group is not explicitly granted permission.

**Comment by monitorjbl** [comment]
This also may be fixed by #39. I pushed a fix for that to the master branch, if you'd like to build and try it out on your instance to see if it resolves the issue.

**Comment by stoleas** [comment]
Hey this is working for me after #39.

**Comment by floryut** [comment]
Ok after #39 and by tweaking the url in config.js group selection are working fine
