### ISSUE TITLE
Groups not appearing in PR Harmony settings at the repo level if not explicitly given permissions at the project level

### ISSUE THREAD

**Issue by wayofthepie** [monitorjbl/pr-harmony#39]
If a group is given permissions to access a repo, at the repo level, they are not appearing in the PR Harmony settings for that repo. They must be given permissions at the project level before PR Harmony finds them.

This is in v2.2.0. I wonder, is this the desired behaviour? 

It seems like it would be more flexible to allow groups to be picked up from repo permission settings, then groups can be added to a repo and not allow them access to the whole project too.

Thanks!

**Comment by monitorjbl** [comment]
Yeah, this looks like a bug. The two config pages need to use different REST endpoints to look up groups. I'll push a fix for that.
