### ISSUE TITLE
DataCenter compatibility for the pr-harmony

### ISSUE THREAD

**Issue by gawlik** [monitorjbl/pr-harmony#41]
Hello,

We just started testing that add-on on the BitBucket DataCenter. If everything goes fine, could you add:
`<param name="atlassian-data-center-compatible">true</param>`
to the atlassian-plugin.xml for the next released version?

Tested versions:
_BitBucket: v4.5.1 and v4.0.1
Add-on: 2.3.0_

Thank you

Michal

**Comment by carlmot** [comment]
Tested the plugin (2.3.0) in a 2 node DC (4.5.1) - manual testing - checked function of each option.  No DC related issues found.
*Edit - Full test was under 4.0.1 and was ok but had the auto merge issue.
Retest with 4.5.1 and the auto merge worked. Did not do full test with 4.5.1 (appears to be issue with user names with newer versions of BB).

**Comment by monitorjbl** [comment]
Sure, I can do that. Thanks for letting me know it works on DataCenter!

**Comment by gawlik** [comment]
Thanks!
