### ISSUE TITLE
Number of users in groups too limited

### ISSUE THREAD

**Issue by kbrnsr** [monitorjbl/pr-harmony#47]
Don't know if this goes for anyone else, but we had a group of 30 users (synched via Crowd), and a few of them aren't allowed to approve a PR. We removed a user from the group and it still remained with 27 users, but one of those who couldn't approve, could again (tested via rest api browser).

Problem seems to be with this line of code: [dereferenceGroups(List<String>#40](https://github.com/monitorjbl/pr-harmony/blob/master/src/main/java/com/monitorjbl/plugins/UserUtils.java#L40)

It should be set to a higher value than 25

**Comment by rinnnn** [comment]
It just worth to say that there were actually two groups, one containing 2 users and other containing over 25 of them. Hence the number 27.

**Comment by kenjiqq** [comment]
Is there a good reason to have a hard-coded limit at all. It should just handle however many users there are in the group

**Comment by monitorjbl** [comment]
No, that's just the way you have to interact with the user API. I meant to make that expand as needed, but never got around to it :( This is definitely a bug that needs fixing, I'll take a look at it. 

On a related note, 30 people is a lot to add to a PR. I've never tried with more than a handful, I wonder if there's a limit to that...

**Comment by kenjiqq** [comment]
We don't add 30 people to a PR. We have a group with 30 members that is setup as a "required group" in PR harmony and then we have "number of reviews" set to two. So two people from the group of 30 have to approve the PR. 
And the issue then is that the users with an index over 25 do not count towards this required number of reviews.
So you cannot open a PR if you just add two approves and one of them have index 25+, or merge a PR with multiple reviewers added if one of the two that have approved it has index 25+

**Comment by monitorjbl** [comment]
You can't add groups to PRs in Bitbucket. The plugin dereferences the group into a list of users and then adds them all to the PR. Only 2 of them have to approve,but all members of the group (well, up to 25 right now) will be added to the PR as reviewers.

**Comment by kenjiqq** [comment]
Maybe we mean different things when we say add as reviewer? 
We don't use the "default reviewer groups" option, so the users in the group are not automatically added on the PR. The developer have to manually add a minimum of two users from the required reviewer group to be able to open their PR.

**Comment by monitorjbl** [comment]
Ah, sorry, the terminology is kind of overloaded here. I get what you're saying, and that sounds totally reasonable.

**Comment by monitorjbl** [comment]
The Marketplace is currently down for maintenance, but a release with this fix is available here: https://github.com/monitorjbl/pr-harmony/releases/tag/v2.3.2

**Comment by monitorjbl** [comment]
Marketplace is back up! The fix is now available, so I'm going to close this issue now.
