### ISSUE TITLE
If reviewer is no longer a valid user, no default users are displayed on PR.

### ISSUE THREAD

**Issue by tamut98** [monitorjbl/pr-harmony#49]
We use AD.  We had a user that was no longer with the company listed as default user for a project ... with several other default user as well... When someone submitted a PR for the project, no users were present.

The work around was simple, remove the user from the default reviewers list.  It would be cool to have this done automatically or at least warn the user that their Default user list was not longer valid, i.e. have a check in place that alerts the submitter that there is user that is invalid in their default user list....  There were 8 users in this list btw.  If it were 1 or 2 that workaround would be easy to deal with.

**Comment by monitorjbl** [comment]
The Marketplace is currently down for maintenance, but a release with this fix is available here: https://github.com/monitorjbl/pr-harmony/releases/tag/v2.3.2

**Comment by monitorjbl** [comment]
Marketplace is back up! The fix is now available, so I'm going to close this issue now.
