### ISSUE TITLE
Non-Lowercase Usernames Do Not Work

### ISSUE THREAD

**Issue by josephearl** [monitorjbl/pr-harmony#5]
Steps to reproduce:
1. Add a user "testuser1" to JIRA/Stash
2. Add a user "TestUser2" to JIRA/Stash
3. Enter "testuser1, TestUser2" in the default reviewers section
4. Save
5. Observe saved value is "testuser1, testuser2"
6. Create a PR
7. Only "testuser1" is added

I think this comes down to:
- The plugin shouldn't lowercase names
- The plugin should correctly handle non-lowercase names

**Comment by monitorjbl** [comment]
Ah, didn't know you could have uppercase letters in a Stash username. I'll back out the fix for #4 in the next release.

**Comment by josephearl** [comment]
No, neither did I until someone on our IT support decided to be "helpful" and capitalise the start of users first/last names.

**Comment by monitorjbl** [comment]
This is now available in version 1.4 on the Atlassian Marketplace.

**Comment by josephearl** [comment]
Great work, thanks!

**Comment by andyliu38** [comment]
Hi, I'm using version 2.3.1 of PR Harmony and it seems like if the user name is all capitalized rather then lowercase (in LDAP), then that user will not be able to approve any pull-request. Could this be a regression bug?  Thanks.
