### ISSUE TITLE
Branch name does not support wildcard

### ISSUE THREAD

**Issue by davfifa** [monitorjbl/pr-harmony#6]
Under "Automerge Pull Requests", "Block Direct Commits" and "Block Pull Requests", branch names entered has to be exact and currently exist in the repo.

Branch names with wildcard like "release/*" cannot be saved.

In the gitflow model, "bugfix/_" branches could be merged against "release/_". Having the ability to automerge would skip the need of manually clicking "Merge" an approved PR.

**Comment by monitorjbl** [comment]
I think this is a great idea! I'll add it to the next release.

**Comment by monitorjbl** [comment]
It occurred to me that the current functionality may not work for your needs. The plugin will only automerge PRs opened _to_ the branches you specify. It sounds like you need an additional specifier to allow you to automerge PRs opened _from_ branches you specify.

I added that option in that last commit. At this point, I don't know if I want the plugin to get into the business of enforcing rules like, "only PRs from branches matching regex A can be merged into branches matching regex B". That's pretty complex to define and properly react to, but hopefully this will work for your needs.

**Comment by davfifa** [comment]
Thanks for the active feedback!

No, I think "to" serves the purpose already.
e.g. from "bugfix/_" to "release/_"

Will wait for your marketplace update, cheers! :+1:

**Comment by monitorjbl** [comment]
This is now available in version 1.4 on the Atlassian Marketplace.
