### ISSUE TITLE
Reviewers field autocomplete not finding users when PR Harmony is enabled.

### ISSUE THREAD

**Issue by lewisgaines** [monitorjbl/pr-harmony#61]
I am running into an issue where certain users do not populate in the Reviewers autocomplete when attempting to add them to a pr. This issue only happens when PR Harmony is enabled, but once disabled the user comes right up when I start typing their name. This is not an issue for everyone, but seems to be limited to users that have the same first name or same/similar first name to last name. In my example picture I have 2 users with the first name Robert so when I try to add them as a reviewer I get "No matching users found". If I try to add a user whose last name is Roberts I also get "No matching users found". I encounter this issue no matter what group I add as required reviewer even with no similarly named users in the group.

I am using Atlassian Bitbucket v4.10.1 and PR Harmony v2.3.5.

![prharmony](https://cloud.githubusercontent.com/assets/10100081/23522850/8cbb5096-ff52-11e6-9703-a049487a5e96.jpg)

**Comment by lewisgaines** [comment]
Appearently this was due to project level settings and I did not figure that out earlier. This is a non-issue.

**Comment by mcohoon** [comment]
@lewisgaines can you add details as to what that project setting was? I am still seeing a similar issue
