### ISSUE TITLE
Remove approvals after work needed is checked.

### ISSUE THREAD

**Issue by ivolator** [monitorjbl/pr-harmony#66]
I think it makes sense, after more work is needed and a new commit has been pushed, to disable the  merge based on previous approves.
Currently if you are blocked by "more work needed" it only takes a minor tweak commit to enable the merge back (if previously approved by other peers).

Case:
1. 2 approvals needed.
2. 2 approve but third person clicks "more work needed"
3. Now we are at a stage where merge is disabled.
4. Committer commits a whole new change but since there were enough approvers the merge is enabled again without the new code being reviewed.

I think approvals should be cleared out at this point.

**Comment by monitorjbl** [comment]
Approvals can be cleared out automatically on pushes in the latest versions of Bitbucket. You can control it in the Pull Requests settings on the repo. I don't think this feature is needed, so I'm going to close the issue for now.
