### ISSUE TITLE
Required reviewer user/group is auto-added as default reviewer

### ISSUE THREAD

**Issue by davfifa** [monitorjbl/pr-harmony#7]
Currently user/group added to "Required reviewer" will be added as default reviewer as well, so the option actually means "Required and default reviewer user/group".

Now our use case is, we want NO default reviewer but still enable automerge upon 2 approvals, is this achievable?
If we do not set default/required reviewer, then auto merge won't work.

Is it possible to separate the "Default" and "Required" conditions?
We can then do:
- automerge upon 2 approvals
- no default reviewer
- required reviewer group

Thanks!

**Comment by monitorjbl** [comment]
I'm not sure I follow. The only thing that "Required Reviewers" does is add users to the PR and validate that  at least a certain number of them have reviewed it.  If you require a user or group of users to approve a PR, then logically they _must_ be added to the PR. 

If you were hoping that you could just drop in a single "reviewer" that happened to be a group, I'm afraid that isn't possible. Stash requires that all reviewers be users; the plugin just makes life a bit easier for you by fetching and adding all the users for the group you specified.

**Comment by davfifa** [comment]
Sorry for making it complicated.

In a simple scenario, can automerge work without setting any default/required reviewer? Currently it seems not.

**Comment by monitorjbl** [comment]
Ah, I suppose it wouldn't. The only thing automerge listens to in the current version is approval events. Mind if I rename this issue to "Branches do not automerge if there are zero required approvers"?

**Comment by davfifa** [comment]
Let me explain it again with an example.

There are user1 to user10, i want to set user1 and user2 (only two) as default reviewers, but any 2 approvals from user1 to user10 would trigger automerge.
- Create PR, seeing user1 user2 as default reviewer
- Manually add user6 and user7
- User1 user7 approved
- Automerge (wont happen now)

What the current version cannot do here is, recognizing user6 and user7, since they are not set as default/required reviewer.

If we can make "Required reviewer" be checked only upon approval event, but won't be added as default reviewers, then it will work:
- Default = user1, user2
- Required = user1, user2, ..., user10
- Number = 2

**Comment by monitorjbl** [comment]
Hm, I think this actually would work now, you would just have use standard "Pull Requests" config screen to use Stash's Number of Approvals setting in addition to PR Harmony's automerge config. The plugin ought to work that way, the automerge check method should respect both settings.

**Comment by davfifa** [comment]
Yes that's what we expect, but it doesn't work.

Configs:
- "Pull requests" config - Requires 1 approver
- PR Harmony - all default/required reviewer = all blank
- PR Harmony - Automerge PR - "develop"
- PR Harmony - # of reviews - "1"

Steps:
1) "user2" creates PR to "develop" branch, adds "user1" as reviewer
2) "user1" approves
3) Automerge doesn't happen - highlighting the exclamation mark shows "1 more approvals required from the following users:" (blank list)

**Comment by monitorjbl** [comment]
If you take out just this part, it ought to work:
- PR Harmony - # of reviews - "1"

That config option sets a threshold for the number of required reviewers that must approve. If you don't have any required reviewers, then you can't ever reach it.

**Comment by davfifa** [comment]
Tried before and just tried again, removed the "# of reviews" from PR Harmony.

Now after 1 approval, the Merge button is enabled, still not auto-merging.

If it ought to work that means it's a bug?

**Comment by monitorjbl** [comment]
Hm, it actually should work as-is. Have you refreshed the screen after clicking Approve?  If it hasn't merged, then it's a bug and I'll have to take a closer look at it. As long as you've fired off an approval, it should have properly triggered. 

If you have a second approval, does it work? I'm wondering if maybe the stash api I used to check the canMerge status is not yet updated when the event fires.

**Comment by davfifa** [comment]
Yes I did refresh the page, nothing happens.

I just tried adding another reviewer and then approve, still the same.

Look forward to your update, thanks! :+1:

**Comment by monitorjbl** [comment]
I just tried this with the latest development version and it worked. Here's what I used (all other settings are left at their defaults):
- PR Harmony - Automerge PR: "master"
- Pull Requests - Requires 1 approvers

Then I did the following:
1. Created a PR as user1
2. user2 approved it.
3. PR is automerged

**Comment by monitorjbl** [comment]
I tried the same thing in 1.3 and it worked as well. What version are you seeing this with?

**Comment by davfifa** [comment]
Strange then, I just re-try again with "master", PR Harmony 1.3 from marketplace.

"Pull requests" - Requires 1 approver
all others unchecked

"PR Harmony" - Automerge pull requests = "master"
all others blank or zero.

"Hooks" - only enabled a "Reject Force Push"

Under "Add-ons", only "PR Harmony" and "Leaderboard" got installed.

No branch/repo permission set.
- Create PR with user1
- user2 approve
- Merge button got enabled, but not automerge still

Any other possible settings triggering a conflict?

**Comment by monitorjbl** [comment]
Could you provide some screen shots of the PR and the repo settings?

**Comment by monitorjbl** [comment]
Also, what version of Stash are you using? I was testing with 3.9.1

**Comment by davfifa** [comment]
Surprisingly found out we are running Stash 3.3.1 here... could be API differences causing the behaviour?

**Comment by davfifa** [comment]
Screenshots of settings:
![screen shot 2015-06-23 at 11 25 28 am](https://cloud.githubusercontent.com/assets/3389161/8298388/cb183c0e-199a-11e5-92e6-038fdaefde08.png)
![screen shot 2015-06-23 at 11 25 34 am](https://cloud.githubusercontent.com/assets/3389161/8298389/ccebc906-199a-11e5-8002-2e18b3294484.png)
![screen shot 2015-06-23 at 11 26 52 am](https://cloud.githubusercontent.com/assets/3389161/8298391/d04fa360-199a-11e5-8251-53f191d8d2c4.png)
![screen shot 2015-06-23 at 11 26 04 am](https://cloud.githubusercontent.com/assets/3389161/8298393/d4985ade-199a-11e5-8a90-ca431556b7c6.png)

**Comment by monitorjbl** [comment]
Yeah, the plugin only supports back to 3.6.1. You should probably upgrade your Stash :)

**Comment by davfifa** [comment]
Oh nooo, Stash should not let us install or even search incompatible plugins/hooks should they? :(

**Comment by monitorjbl** [comment]
It should warn you, but I don't think it will stop you. The plugin has the compatibility range defined in the marketplace (3.6.1 - 3.9.1)

**Comment by davfifa** [comment]
Anyway in this case, the issue is probably invalid, until it happens again on 3.6.1+, thanks!
