### ISSUE TITLE
Setting # of required reviewers should warn about empty required reviewers field

### ISSUE THREAD

**Issue by j-vizcaino** [monitorjbl/pr-harmony#8]
When setting the number of required reviewers needed to approve pull requests, you can still save the configuration while having an empty required reviewers list.
This is troublesome because, once reviewed, the pull request still cannot be merged and the message is akward (because there is no one in the list).

**Comment by monitorjbl** [comment]
Yeah, I see what you mean. I think adding a warning to the config UI would be a good idea.
