### ISSUE TITLE
Add autocomplete of users and group fields

### ISSUE THREAD

**Issue by j-vizcaino** [monitorjbl/pr-harmony#9]
Typing login is efficient but not too user-friendly.
Having autocomplete fields would be really cool.
Bonus: display the users/groups like the view showing repository permissions in Stash.
For a user or group, you should be able to check/uncheck default reviewer, required reviewer.

Thank you.

**Comment by monitorjbl** [comment]
I think this is a good idea, but I'd like to see if there's any Stash-provided APIs for rendering the dropdowns. I don't want to have a custom version that has to keep up with their UI changes. I'll see what I can find to do this.

**Comment by spoage** [comment]
I believe this is what you're looking for: https://docs.atlassian.com/aui/latest/docs/auiselect2.html

Hope that saves you a bit of time. :) I'd love this feature as well.

**Comment by monitorjbl** [comment]
Nice! That looks pretty simple to add in, I'll see what I can do with it.

**Comment by monitorjbl** [comment]
So, this is implemented, but it's not going to look exactly like the other dropdowns you see in Stash. All of the dropdowns I've seen for users have the full name and email included to the select options. The config that is stored for the plugin is simply a list of Strings, so the full name/email is not available to the dropdown. 

I didn't want to change up all of the config logic to add what would really just be a cosmetic detail that's only used for the dropdowns. It may be possible to work them in somehow in the future, but for now the config screen will just look like a prettier version of the comma-separated list. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/1149136/9296210/6b25f576-4455-11e5-8a7a-824687a10954.png)

**Comment by j-vizcaino** [comment]
Thank you! It looks better now. I'll give it a try when I get back from holidays.

**Comment by monitorjbl** [comment]
The beta release of this version is now available on GitHub here: https://github.com/monitorjbl/pr-harmony/releases/tag/v1.7-RC1. If you have a few minutes to try it out, I'd love to get your feedback before I release it out to the marketplace

**Comment by mnhorak** [comment]
A couple comments:
- The default and required users/groups are no longer comma-separated, so you can change the labels on the settings screen.
- The exclude users/groups are still the comma-separated style. Should those be auto-complete as well?

**Comment by monitorjbl** [comment]
Ah, thanks! Totally forgot about those fields, I'll get those and the labels updated.
